### ISSUE TITLE
Hyperlinks in column cells stopped working recently

### ISSUE THREAD

**Issue by dajavous** [PablocFonseca/streamlit-aggrid#119]
I have been successfully using this very useful package, and until recently could implement hyperlinks in a column with the code:

`gb.configure_column("ISSUE",
                            headerName="ISSUE",
                            cellRenderer=JsCode('''function(params) {return '<a href="https://thebcd.co.uk/issue_' + params.value + '" target="_blank">'+ params.value+'</a>'}'''),
                            width=300)`

which would result in a hyperlink to an address related to the cell value. 

On editing a different part of of my app, I now find that instead of creating a hyperlink to the address, the html text is written to the screen instead:

`<a href="https://thebcd.co.uk/issue_1" target="_blank">1</a>`

rather than the hyperlink <a href="https://thebcd.co.uk/issue_1" target="_blank">1</a> to the address. Any help appreciated.

**Comment by PablocFonseca** [comment]
I'm checking this issue, please use the previous version meanwhile

**Comment by PablocFonseca** [comment]
Should be working in 0.3.2

I had to downgrade ah-grid-react to 6.2.0

**Comment by dajavous** [comment]
Thanks. I'm out all day today, so will try it tomorrow.

Regards,

David Armstrong.

**Comment by rafaela00castro** [comment]
I'm using the new version (0.3.2), but the link still doesn't work. @dajavous did you do something different? 
I can't use the previous version (0.2.3.post2) because in this version the nested grid isn't working.

![image](https://user-images.githubusercontent.com/8461113/182692874-a6cfb437-4c23-4f40-a555-0d897555f554.png)

**Comment by dajavous** [comment]
The full app listings (app.py and short.py) are in my public repository at https://github.com/dajavous/thebcd-public, with the apps at https://dajavous-thebcd-public-short-yihtck.streamlitapp.com/ and https://dajavous-thebcd-public-app-ztufun.streamlitapp.com/

**Comment by rafaela00castro** [comment]
Thanks @dajavous for your reply. And links are working fine in the first grid, but I didn't have the same luck when I tried to add in the second grid (using nested grid).

@PablocFonseca do you have any workaround for that?

![image](https://user-images.githubusercontent.com/8461113/183227123-b8dab0d0-5b0f-44e7-b5d2-511050c3eb4b.png)

Code extracted from [here](https://github.com/PablocFonseca/streamlit-aggrid-examples/blob/main/nested_grids.py).

````
    # provide Detail Cell Renderer Params
    "detailCellRendererParams": {
        # provide the Grid Options to use on the Detail Grid
        "detailGridOptions": {
            "rowSelection": "multiple",
            "suppressRowClickSelection": True,
            "enableRangeSelection": True,
            "pagination": True,
            "paginationAutoPageSize": True,
            "columnDefs": [
                {
                    "field": "callId", 
                    "cellRenderer": JsCode('''function(params) {return '<a href="https://www.google.com" target="_blank">' + params.data.callRecords.callId +'</a>'}'''),
                },
                {"field": "direction"},
                {"field": "number", "minWidth": 150},
                {"field": "duration", "valueFormatter": "x.toLocaleString() + 's'"},
                {"field": "switchCode", "minWidth": 150},
            ],
            "defaultColDef": {
                "sortable": True,
                "flex": 1,
            },
        },
        # get the rows for each Detail Grid
        "getDetailRowData": JsCode(
            """function (params) {
                console.log(params);
                params.successCallback(params.data.callRecords);
    }"""
        ).js_code,
    },
````

**Comment by dajavous** [comment]
Replacing the cellRenderer line with the following works:

"cellRenderer": JsCode('''function(params) {return '<a href="https://google.com" target="_blank">'+ params.value+'</a>'}'''),

**Comment by rafaela00castro** [comment]
@dajavaus , thank you very much for your help. It's working, after I followed your kind instructions!!
Now I can see what my problem was :)
